@startuml config_usecase_shared_dedicated
component "Mixed Instance" as Inst
interface "Primary Interface" as Iface

interface "Shared EP (40001)" as E1
interface "Dedicated EP (40002)" as E2

Inst -- E1
Inst -- E2

note right of E1
  <b>Service A</b>
  <b>Service B</b>
end note

note right of E2
  <b>Service C</b>
end note
@enduml
