@startuml system_overview

skinparam backgroundColor #FEFEFE
skinparam componentStyle rectangle

package "Fusion Hawking Stack" {
    [Rust Core Library] as Core
    [Python Runtime] as PyRT
    [C++ Runtime] as CppRT
    [JS/TS Runtime] as JsRT
    [Code Generator (IDL)] as Codegen
    [Automation Toolkit] as Fusion
}


package "Application Layer" {
    [Rust Application] as RustApp
    [Python Application] as PyApp
    [C++ Application] as CppApp
    [JS/TS Application] as JsApp
}


package "Network Layer" {
    [UDP Transport] as UDP
    [TCP Transport] as TCP
    [Multicast (SD)] as Mcast
}

RustApp --> Core
PyApp --> PyRT
CppApp --> CppRT
PyRT ..> Core : "Same Protocol"
CppRT ..> Core : "Same Protocol"
JsRT ..> Core : "Same Protocol"
JsApp --> JsRT


Core --> UDP
Core --> TCP
Core --> Mcast

Codegen --> RustApp : generates
Codegen --> PyApp : generates
Codegen --> CppApp : generates
Codegen --> JsApp : generates
Fusion --> Core : builds & tests


@enduml
